@hostname = localhost
@port = 4567
@host = {{hostname}}:{{port}}
@token = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJlZGMiLCJzdWIiOiJlZGMiLCJleHAiOjE2NzYzODE1ODksIm5iZiI6MTY3NjM3Nzk4OSwiaWF0IjoxNjc2Mzc3OTg5LCJhdWQiOiJpZHNjOklEU19DT05ORUNUT1JTX0FMTCIsInNjb3BlIjpbIm9tZWpkbjpyZWFkIiwib21lamRuOndyaXRlIiwib21lamRuOmFkbWluIiwiZW1haWwiLCJwcm9maWxlIiwib3BlbmlkIl19.VZpPdIeRRRlSS6DcupBJqjPFwDDWZfA8SCap7A8_ZbqOcSTVW08kFHWM1G2ZGnN18xSlt3NSJdnUrm-GVIb6Y6bbOTF1kXSIXwZ2lc4FTT_FnQ54B2zHQbNHagjR-uQnfMFcY-_S2zC4TE_1UC7eRuSKvhi0RP2Bl75hrUe2uieX_7RoSDY6o-9uEj2T1k233YUskDmJ0Cp5yr7Ydvt2S1FV7pw_Eo3s-L_wAC0a4lQ5DHvy0qKJWZGFFZrJDz3sqIeVIyQkLbz7EEcQF29XBLHSdhmjuqX0TYxic2HIV7qX067IcXt2XKjzsaYk4NP4y88XyWy3SPwsmBa3qulzgA
@grantType = client_credentials
@client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer
@scope = openid profile omejdn:admin idsc:IDS_CONNECTOR_ATTRIBUTES_ALL

### Get JWKS
GET http://{{host}}/jwks.json HTTP/1.1
Content-Type: application/json

### Get OpenId Configuration
GET http://{{host}}/.well-known/openid-configuration HTTP/1.1
Content-Type: application/json

### Get Token
POST http://{{host}}/token HTTP/1.0
Content-Type: application/x-www-form-urlencoded

grant_type={{grantType}}
&client_assertion_type={{client_assertion_type}}
&client_assertion={{token}}
&scope={{scope}}
